const adicionarPalavra = document.getElementById("nova-palavra")
const input = document.getElementById("input-nova-palavra")
const iniciar = document.getElementById("iniciar-jogo")
const lista = document.getElementById("lista")
let palavras = []
let errors = [];
const canvas = document.getElementById("forca");
canvas.style.display="none"
let ctx = canvas.getContext('2d');
let strokeColor = "#0A3871"
let draw = true;
let gameOver = true;
let actualWord = -1
let erroLetterIndex = 0
let scale = 10
let mainx = 110 * scale
let mainy = 110 * scale
let fontSize = 2
let rightChars = []
let currentRightChars = 0
let word = ""
let size = 0
let success = false
let fontStyle = "Verdana"
let fontWheight = "900"
let messagePosition = 3
canvas.width=5000
canvas.height=2500
ctx.lineWidth = 3.5*scale;
iniciar.disabled=true