const adicionarPalavra = document.getElementById("nova-palavra")
const input = document.getElementById("input-nova-palavra")
const iniciar = document.getElementById("iniciar-jogo")
let palavras = []
let errors = [];
const canvas = document.getElementById("forca");
let ctx = canvas.getContext('2d');
let draw = true;
let gameOver = true;
let actualWord = -1
let erroLetterIndex = 0
let scale = 1
let mainx = 100 * scale
let mainy = 100 * scale
let fontSize = 2
let rightChars = []
let currentRightChars = 0
let word = ""
let size = 0
let success = false
let fontStyle = "arial"
let messagePosition = 5
iniciar.disabled=true